baseURL = "https://howtocode.io/"
title = "How To Code"
author = "Robert Guss"
paginate = 12
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
theme = "starters-creek"
enableRobotsTXT = true

[markup.goldmark.renderer]
  unsafe= true

[Author]
  name = "Robert Guss"

[permalinks]
  post = "/:slug/"
  page = "/:filename/"

[outputs]
  section = ["JSON", "HTML"]

[params]
  description = "Tutorials for Web Developers"
  author = "Robert Guss"
  logo = "images/HowToCode_OpenGraph_1200_630.png"
  header = "How to Code"
  twitter = "howtocode_io"
  github = "robertguss"
